### ISSUE TITLE
hostname on xenial is different from trusty

### ISSUE THREAD

**Issue by iainsproat** [cloudfoundry/bosh-linux-stemcell-builder#57] opened 2018-07-25 12:42 UTC
The `hostname` on ubuntu-xenial returns the VM CID.  On ubuntu-trusty, `hostname` returns the BOSH agent ID.

This causes releases which depend on hostname returning agent ID to fail. We've found that the [turbulence-release](https://github.com/cppforlife/turbulence-release/issues/22) is affected by this.

/cc @akshaymankar

**Comment by dpb587-pivotal** [comment] 2018-07-25 15:39
Thanks for mentioning this. Are you noticing this on a particular IaaS(es)?

**Comment by akshaymankar** [comment] 2018-07-25 17:20
@dpb587-pivotal We noticed it on GCP

**Comment by mfine30** [comment] 2018-11-27 00:01
Closing and re-opening to trigger a github story for us to track.

**Comment by davidjahn** [comment] 2018-12-07 00:42
Hi @mfine30 @dpb587-pivotal  this issue has broken our bosh-deployed product (Pivotal Cloud Cache) because an internal component tries (and fails) to resolve this hostname.

Would love if this issue were resolved soon. In the meantime we will probably try some weird workaround like appending the VM CID to `/etc/hosts` or something .. thanks!

**Comment by pivotal-mp** [comment] 2018-12-07 23:53
@iainsproat @davidjahn Could you let us know what Xenial stemcell you're using? We just tried it on GCP w/ the latest Xenial light stemcell (170.12), and `hostname` gives us the `agent_id`.

**Comment by pivotal-mp** [comment] 2018-12-10 21:55
Tried reproducing w/ a whole lot of older stemcells, and got it once on 97.19 - but after that, couldn't reproduce it even on that stemcell. Do you have more details for us to nail this down? Does it happen intermittently, or all the time?

**Comment by iainsproat** [comment] 2018-12-12 10:20
The current behaviour I'm seeing is the following:

```
bosh stemcells
Name                                                                 Version  OS
bosh-google-kvm-ubuntu-xenial-go_agent  170.12*  ubuntu-xenial
```

When ssh'd onto a VM
```
hostname
vm-2cab0e84-6965-46d8-630a-e61a87a5fc17
```

This is the VM CID reported by `bosh vms`
```
Instance                                           Process State  AZ  IPs       VM CID                                   VM Type        Active
worker/501701c8-5287-472d-8fa2-6b1a19cd9a47        running        z1  10.0.1.3  vm-2cab0e84-6965-46d8-630a-e61a87a5fc17  small-highmem  true
```

**Comment by dpb587-pivotal** [comment] 2018-12-13 01:48
Closing - this has been fixed in [v170.13](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/releases/tag/ubuntu-xenial%2Fv170.13) and [v97.41](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/releases/tag/ubuntu-xenial%2Fv97.41). Thanks for raising this issue.

**Closed** 2018-12-13 01:48 UTC
Labels: unscheduled

**Comment by alex-slynko** [comment] 2018-12-13 12:11
Hey @dpb587-pivotal 

I somehow missed it. The previous behaviour where hostname was showing Cloud ID was different but more correct.
It was introduced in #58 and we expect this behaviour in the stemcell and it breaks CFCR on Azure.
Could you please revert it?

The real problem is with Bosh turbulence which expects hostname to equal VM ID.

**Comment by alex-slynko** [comment] 2018-12-13 12:14
cc @mfine30

**Comment by dpb587-pivotal** [comment] 2018-12-13 12:44
@alex-slynko I’m not sure about reverting. In this case we did fix a genuine issue of unexpected behavior for Google stemcells. It was causing mixed behavior of hostnames, so separate from Azure and it would have been causing mixed results in Google. At this point, there should be no change in behavior for Azure stemcells, but let us know if you’re seeing a new error and something specific there.

In terms of a more generic issue, it sounds like you’re suggesting it’s an issue in turbulence? If so, I’d recommend raising an issue in [turbulence-release](https://github.com/cppforlife/turbulence-release).

Regarding Azure’s use of DHCP hostname for DNS registration, we might need to revisit that discussion at some point. Thanks for the reminder about that behavior.

**Comment by voelzmo** [comment] 2018-12-13 12:56
Are we talking about this issue? Or is this something separate?
https://github.com/cppforlife/turbulence-release/issues/22

**Comment by iainsproat** [comment] 2018-12-13 13:31
@voelzmo - yes, it's that issue and [this PR to resolve it](https://github.com/cppforlife/turbulence-release/pull/23)

**Comment by voelzmo** [comment] 2018-12-13 13:36
should also be fixed with https://github.com/cloudfoundry/bosh-linux-stemcell-builder/releases/tag/ubuntu-xenial%2Fv170.13 right?
@alex-slynko: from that issue it seems that turbulence wants the agent-id instead of cloud-id, does that seem different from what you're seeing?

**Comment by iainsproat** [comment] 2018-12-13 13:53
@voelzmo - yes, the 170.13 stemcell fixes turbulence-release. The [turbulence-release#22](https://github.com/cppforlife/turbulence-release/issues/22) issue can be closed, and the [turbulence-release#23](https://github.com/cppforlife/turbulence-release/pull/23) PR becomes redundant.

The reason for @alex-slynko objection is because CFCR has recently been adapted to depend on the altered behaviour in xenial stemcell versions before 170.13 (VM CID instead of agent-id).  If the changes found in 170.13 are to stay, CFCR will have to again change to depend on the new behaviour (hostname returning agent-id).

**Comment by dpb587-pivotal** [comment] 2018-12-14 00:05
I don't have context on CFCR changing behaviors around changing hostname behaviors. If you can provide more information, that would be helpful. Or, if you are actively experiencing issues with these new stemcells, please let us know the actual errors because I don't understand how the change in the most recent stemcell would break things (especially outside of Google Cloud).

I think we may be talking about different things. To clarify a bit:

 * Xenial stemcells should generally have been using the agent ID as the hostname since they were released. I don't think there are any cases where we intentionally use something else.
 * We may have missed the "original issue" that motivated the creation of this issue, but as part of investigating this issue we did discover that some of the Google customizations of the stemcell could cause the wrong hostname to be configured. This could manifest if:
   * race behaviors caused agent's bootstrap hostname configurations to occur after the unintentional Google-specific script; or
   * networking services are restarted (or virtually interrupted by the IaaS).
 * Reviewing the Azure/DHCP setting mentioned earlier, I don't think it is related to setting the hostname of the VM. The purpose of that change was to ensure the hostname (whatever it is) is correctly sent to Azure for internal DNS registration of the VM's IP. I believe this was to enable reverse lookups as part of the Kubelet registration or communication workflows.

Let me know if any of those are misunderstandings, or if there's some other concern I'm not understanding.

Thanks!

**Comment by iainsproat** [comment] 2018-12-14 09:50
@dpb587-pivotal 
Thanks for the further explanations.

We have now [bumped CFCR to work with BOSH stemcell 170.13](https://www.pivotaltracker.com/story/show/162638723), and it is passing our CI.  So all is good.
