### ISSUE TITLE
Partition "/" full caused by Windows Azure Linux Agent(waagent)

### ISSUE THREAD

**Issue by David-Pivotal** [cloudfoundry/bosh-linux-stemcell-builder#107] opened 2019-10-29 02:03 UTC
Hi,

When creating the buildpack, shall we consider installing the Windows Azure Linux Agent(waagent) in another partition, for example `/var/vcap/data`?
Or shall we give a larger size for the `"/"` partition?

In vms deployed in Azure, the Windows Azure Linux Agent(waagent) tries to pull update OMS agent zip files under `/var/lib/waagent`. As the `"/"` partition is quite small and only 3GB, it is unable to extract the zip file due to the space issue. 

This is an example of UAA vm. You can see the`"/"` partition is around 3GB.
`uaa/bf85e3bd-2e76-4a74-8b9d-00ae1c5c70fc:/var/lib/waagent# lsblk`
`NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT`
`sdb      8:16   0    8G  0 disk `
`└─sdb1   8:17   0    8G  0 part `
`sr0     11:0    1  632K  0 rom  `
`fd0      2:0    1    4K  0 disk `
`sda      8:0    0   35G  0 disk `
`├─sda2   8:2    0  3.8G  0 part [SWAP]`
`├─sda3   8:3    0 28.3G  0 part /var/vcap/data`
`└─sda1   8:1    0  2.9G  0 part /`

While installing/updating OMSagent for linux, it fills up `/dev/sda1` mount across all PCF VM's causing high cpu IO time issues in customer side.
`Filesystem Size Used Avail Use% Mounted on`
`/dev/sda1 2.8G 2.3G 328M 88% /`

Regards,
David

**Comment by jaresty** [comment] 2019-10-30 23:03
Hey - we (the bosh team) considered some options for resolving this but we're still discussing as a team and waiting to hear back from others as to why this has not been an issue for anyone else so far.  For now, our recommendation would be to increase the partition size for `/`.

**Comment by David-Pivotal** [comment] 2019-10-31 07:12
Thanks for your comments! @jaresty 

Actually I have received reports about this issue from at least two customers. Please forgive me I cannot share their names here in a public website. It is great to see we can place the waagent lib to the ephemeral disk. Hope this fix could benefit more customers.

**Comment by metskem** [comment] 2019-12-09 09:55
Increasing fs size or moving to a separate fs I would consider that fighting symptoms.
The OMSAgent takes about 140MB, and the backup of that also, so that should easily fit in a 3GB root fs.
The problem is 2-fold:
* when a new version of OMSAgent is installed, a backup is created, but the old backup is not removed
* the waagent does not notice the full root fs, and keeps trying to backup/update the OMSAgent forever

I was told that newer versions of the waagent would fix the second.
MS should fix the first.

**Comment by mofrank** [comment] 2019-12-10 17:43
I am from one of the companies reporting the problem ( Merrillcorp  ) I can confirm that this is an ongoing issue.   We have had, at least, three production outages due to this issue.   I would like to see the location of the waagent libs moved.

**Comment by mbsnl** [comment] 2019-12-20 13:23
Hopefully this will make it to version 2.2.46 of WALinuxAgent.
It should better handle the (temporary) storage and cleanup of downloaded zip files.

https://github.com/Azure/WALinuxAgent/pull/1731

**Comment by mbsnl** [comment] 2019-12-20 13:26
Hopefully this will make it to version 2.2.46 of WALinuxAgent.
It should allow configuration of Logfile rotation schedule and how much to keep.

https://github.com/Azure/WALinuxAgent/pull/1740

**Comment by mbsnl** [comment] 2019-12-20 13:46
Version 2.2.45 already fixed the fail/re-try logic when upgrading extensions, causing High CPU.

https://github.com/Azure/WALinuxAgent/pull/1686

**Comment by vrdmr** [comment] 2019-12-20 21:56
Also the code to cleanup the zips would be deployed with 2.2.46. That should reduce the stray zip files as well.
https://github.com/Azure/WALinuxAgent/pull/1642

**Comment by bureado** [comment] 2020-02-15 19:54
Did the 2.2.46 release address this issue?

**Closed** 2020-07-27 14:33 UTC
Labels: unscheduled
