### ISSUE TITLE
aws stemcell - limited network connectivity due to network driver restarts

### ISSUE THREAD

**Issue by BeckerMax** [cloudfoundry/bosh-linux-stemcell-builder#99] opened 2019-08-01 07:57 UTC
**Symptoms:**
On AWS on the affected VMs we observe problems with the network connectivity. Frequently the network connectivity is down, coming back up shortly after. This is probably related to a restart of the NIC as seen in the logs below. It is independent from the releases running on the managed bosh vm.

The problem will stay indefinitely. To solve it we delete the vm via bosh. We once rebooted a VM which also solved it. 

**Logs:**
kern.log:
```
2019-07-22T11:01:55.096109+00:00 localhost kernel: [2008934.869922] ixgbevf 0000:00:03.0: NIC Link is Up 10 Gbps
2019-07-22T11:02:06.108096+00:00 localhost kernel: [2008945.880952] ixgbevf 0000:00:03.0: NIC Link is Up 10 Gbps
2019-07-22T11:02:11.992109+00:00 localhost kernel: [2008951.765109] ixgbevf 0000:00:03.0: NIC Link is Up 10 Gbps
2019-07-22T11:02:21.972103+00:00 localhost kernel: [2008961.745862] ixgbevf 0000:00:03.0: NIC Link is Up 10 Gbps
2019-07-22T11:02:32.216097+00:00 localhost kernel: [2008971.989764] ixgbevf 0000:00:03.0: NIC Link is Up 10 Gbps
2019-07-22T11:02:42.964105+00:00 localhost kernel: [2008982.737861] ixgbevf 0000:00:03.0: NIC Link is Up 10 Gbps
2019-07-22T11:02:53.208095+00:00 localhost kernel: [2008992.981733] ixgbevf 0000:00:03.0: NIC Link is Up 10 Gbps
2019-07-22T11:02:59.100107+00:00 localhost kernel: [2008998.873855] ixgbevf 0000:00:03.0: NIC Link is Up 10 Gbps
2019-07-22T11:03:10.104101+00:00 localhost kernel: [2009009.877387] ixgbevf 0000:00:03.0: NIC Link is Up 10 Gbps
(...)
```
There are no correlating log entries in the agent or audit.log.

**Impact**
Network calls will occasionally not go through. Usually the VM will report as healthy as the occasional health check goes through. Jobs will still be reported as `running`. VMs that rely on frequent network communication like Diego cells are strongly affected.

As the problem will stay indefinitely we currently need to spot the instances and then use `delete-vm` to delete them manually.

**Reproducibility**
We see this issue only on large installations (>200 Instances). 
We were able to reproduce it by creating a large deployments with 200 instances. Then we recreated instances until the problem occurred. 

**Further information**
Because of this problem the network driver already has been [updated](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/0e0c19d293df6b4910a9d359639e96f31e4fdc69) but this didn't solve or improve the situation.

We communicated this with the AWS support. They suggested us to contact the AMI vendor and gave the following hint on debugging:

``` 
Regarding your set debug mode for ixgbevf driver question, I found the links below and want to share with you on a best effort basis.
You may try to enable the kernel debug or if the driver supports you may use msglvl flag with ethtool.
http://mails.dpdk.org/archives/dev/2017-September/076962.html
https://techedemic.com/2015/01/22/ubuntugrub2-verbose-booting/
```
The AWS support suggested to use the AWS kernel which includes the ixgbevf driver but our assumption that this is not possible on a stemcell.

cc @friegger @achawki

**Comment by aashah** [comment] 2019-08-06 17:11
> The AWS support suggested to use the AWS kernel which includes the ixgbevf driver..

Not sure I understand their support's ask, as we have the driver as well. As far as turning on debug, this is probably something that could be done on the VM by rebuilding the ixgbevf driver, on the running VM, with some flags on. Maybe we can both look into trying that (at least until we can figure out reproducing).

On a separate note, I'd like to hear more about your reproduction steps before we go off creating 200 instances.

**Comment by achawki** [comment] 2019-08-07 13:40
>Not sure I understand their support's ask, as we have the driver as well. 

AWS would support us in troubleshooting only if we were using the AWS kernel. In case we are using the stemcell, which side loads the driver, we are more or less on our own.

> As far as turning on debug, this is probably something that could be done on the VM by rebuilding the ixgbevf driver, on the running VM, with some flags on. 

That sounds good.

> On a separate note, I'd like to hear more about your reproduction steps before we go off creating 200 instances.

In the past we just recreated diego cells until they failed to start up because a pre-start script failed due to limited network access. We are going to provide a minimal reproduction scenario and come back to you once we have it.

cc @BeckerMax

**Comment by aashah** [comment] 2019-08-14 17:18
I spoke with my pair today, @jaresty, about this issue. He brought up a super interesting theory.

On Xenial stemcells, the bosh-agent uses `ifupdown` to manage the network. This puts a lot of the responsibility of ensuring the network devices are configured correctly on the bosh-agent. The bosh-agent basically only performs these actions on process start. If the interface goes does, the agent does not recover.

This may explain why rebooting, or recreating the VM has been successful for you.

The fix probably involves moving to a network supervisor like NetworkManager, systemd-networkd, or netplan.

We have begun making this change, of moving from ifupdown -> systemd-networkd, in the next xenial & bionic lines.

What do you think?

**Comment by achawki** [comment] 2019-08-23 12:44
We tried to reproduce the issue with following script. It can be any bosh deployment. For simplicity we took https://github.com/cppforlife/zookeeper-release

```
#!/bin/bash

set -euo pipefail

while true; do
  OUTPUT="$(bosh -e bosh -d zookeeper ssh zookeeper -c 'sudo su -c "occurrences=\$(cat /var/log/kern.log | grep \"NIC Link is Up\" | wc -l); if [ \$occurrences -gt 4 ];then echo ISSUE FOUND on \$(< /var/vcap/instance/name).\$(< /var/vcap/instance/id); fi;"')"
  if grep "ISSUE FOUND" <<<"$OUTPUT";then
    exit 1
  fi
  echo "Recreating zookeeper instance group"
  bosh -e bosh -d zookeeper recreate zookeeper -n
  sleep 300 # sleep after recreate so the potential problem can be seen in the logs
done
```

We tried it with a deployment size of `50` and `max_in_flight` also set to `50`. The script ran for multiple days on two different installations. So far we could unfortunately not reproduce the problem. We will continue trying to reproduce it.

>I spoke with my pair today, @jaresty, about this issue. He brought up a super interesting theory.

Sounds interesting. An affected instance will not recover, but the problem is rather intermittent. Not all network connections fail. `Bosh` also considers the vm as `healthy`. When I understand the theory correctly, no network connectivity at all should be possible in this situation?

**Comment by friegger** [comment] 2020-08-14 06:39
We still see this issue regularly on all regions on AWS. It seems to randomly hit a VM independent of what is deployed on that VM, roughly 1/1000 VMs. If no monitoring is in place it might go unnoticed until the VM is recreated the next time, but it can have severe impact as described above. We really wonder why there are not reports from others.

Meanwhile we have better monitoring in place and are able to catch affected instances before they are recreated. We then can `bosh ignore` that instance.

Recent contact with AWS support have again resulted in pointing out that they can only provide limited support since the stemcell is a custom image. Rebooting the VM usually helps. Affected instances are affected right after hey have booted. So we assume the issue occurs during boot somewhere between VM start and the agent finishing up everything.

For context, this issue is with us since 2017, already with trusty stemcells. Meantime the driver has been updated a few times, we have switch to xenial, but the issue persists.

@mrosecrance Is there still someone available on your side with deeper stemcell knowledge that we could pair with looking into an affected VM?

**Comment by mrosecrance** [comment] 2020-08-19 19:47
The change mentioned by Aakash above (ifupdown -> systemd-networkd) is only in the 621 line. Is the issue still popping up? It's possible that there's more checking that needs to be done on startup.

At the moment we don't have anyone with deep stemcell knowledge but it's context we'll need to gain anyway so open to pairing on this issue.

**Comment by jsievers** [comment] 2020-09-03 10:47
we still see the issue happening on a low percentage of AWS VMs.

we verified on an instance showing the issue that

```
systemctl restart systemd-networkd
```

does not help

also, reboot of the instance does not help. we even downloaded, compiled the kernel module to 4.7.1 from https://sourceforge.net/projects/e1000/files/ixgbevf%20stable/ , then loaed it using modprobe, did not help either

**Comment by friegger** [comment] 2020-09-03 15:38
Did another test with updating the driver:
```
bosh -e <env> -d <deployment> scp ixgbevf-4.8.1.tar.gz <instance>:/tmp/.
cd /tmp
mkdir /usr/src/ixgbevf-4.8.1
tar -xzf ixgbevf-4.8.1.tar.gz -C /usr/src/ixgbevf-4.8.1 --strip-components=1
# copy content from https://raw.githubusercontent.com/cloudfoundry/bosh-linux-stemcell-builder/master/stemcell_builder/stages/system_ixgbevf/assets/usr/src/ixgbevf-4.6.1/dkms.conf to /usr/src/ixgbevf-4.8.1/dkms.conf and adjust version
dkms -k 4.15.0-112-generic add -m ixgbevf -v 4.8.1
dkms -k 4.15.0-112-generic build -m ixgbevf -v 4.8.1
dkms -k 4.15.0-112-generic install -m ixgbevf -v 4.8.1
modinfo ixgbevf #-> new version
rmmod ixgbevf && modprobe ixgbevf
ethtool -i eth0 #-> new version
```

The issue persisted.

A reboot with `sudo systemctl reboot` fixed the issue on that specific instance.


Another remark. The ixgbevf driver is only used on non-nitro instances. On nitro instances the `ena` driver is used. Currently we mostly use non-nitro-based instances. Thus, we don't know whether the problem exists on nitro instances.

**Comment by beyhan** [comment] 2020-11-16 10:44
We investigated this issue further and have the following findings:
* the issue happens on AWS with instance types (e.g. m4.large or m4.xlarge...), which use the ixgbevf driver by default.
* the custom Intel driver ixgbevf is using two queue pairs (RX, TX) by default.
* the kernel module driver ixgbevf for Xenial and Bionic is using a single queue pair by default.

The AWS is using DPDK (https://dpdk.readthedocs.io/en/v17.11/nics/intel_vf.html) on the host system, which supports one queue pair only. This has been confirmed by AWS support. This is to root cause of the initial problem, because the second transmit queue is timing out, which triggers a restart of the NIC driver. Using the latest bionic stemcell with the kernel module driver we couldn't find any issues. We recommend here to use the kernel module driver in bionic to solve this problem.

**Comment by friegger** [comment] 2020-11-16 13:40
@dlresende Would you also consider a fix for Xenial? It's a bug, on the other hand is end of live approaching.

**Comment by StefanWutz** [comment] 2020-12-03 17:11
I did another test trying to disable the multi queue feature during build process:

I changed the following line in file /usr/src/ixgbevf-4.6.1/dkms.conf
```
MAKE="cd src/; make BUILD_KERNEL=${kernelver}"
```
to
```
MAKE="cd src/; make BUILD_KERNEL=${kernelver} KBUILD_CFLAGS_MODULE=-DIXGBEVF_MAX_RSS_QUEUES=1"
```
and rebuild the driver
```
dkms remove -k $(uname -r) -m ixgbevf -v 4.6.1 && dkms add -k $(uname -r) -m ixgbevf -v 4.6.1 && dkms install -k $(uname -r)  -m ixgbevf -v 4.6.1
```
Interestingly the change matches the kernel module driver ixgbevf version 4.1.0k.
```
DKMS: build completed.

ixgbevf.ko:
Running module version sanity check.

Good news! Module version 4.1.0-k for ixgbevf.ko
exactly matches what is already found in kernel 4.15.0-123-generic.
DKMS will not replace this module.
You may override by specifying --force.
```

While using the mentioned ```--force``` parameter in the command ```dkms install --force ...``` will work, replacing the compiled module by using ```rmmod ixgbevf && modprobe ixgbevf``` leads to an unresponsive vm.

A redefinition of _IXGBEVF_MAX_RSS_QUEUES_ to 1 inside the source code works as expected.

**Comment by friegger** [comment] 2020-12-10 05:10
@mrosecrance Given that DKMS states that the configuration would be identical to the kernel version the easiest solution might be to just remove the custom Intel driver. What do you think?

**Comment by mrosecrance** [comment] 2020-12-10 23:39
After some digging it looks like we initially moved to a custom intel driver as part of [this pr](https://github.com/cloudfoundry/bosh/pull/860) and from the [aws docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/sriov-networking.html) it looks to just affect m4 instances + a few others.

Since we're well beyond the version that caused us to move forward for `sriov_net_support` it seems pretty safe to rip out.

On a related note, if enhanced networking on newer instance types is a desired feature we can look into [ENA support](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking-ena.html#enhanced-networking-ena-linux) later.

**Comment by friegger** [comment] 2020-12-11 08:12
Thanks @mrosecrance! Do I understand it correctly, that you would bring in a PR that removes the custom driver then?

Regarding ENA support, on Nitro based instances the kernel ENA driver is already used and seems to work fine.

**Comment by thoHeinze** [comment] 2021-01-13 12:05
@mrosecrance  Any update on this issue? We are heavily impacted by this problem and would be interested to understand the plan forward with this issue. Will you provide a fix for the xenial stemcell? Is the issue already fixed in the bionic stemcell?

**Comment by mrosecrance** [comment] 2021-01-13 17:52
Xenial is going out of general support in April so I don't think it makes sense to backport for only the last 3-4 stemcell patches. I haven't seen a PR for a fix yet for Bionic.

**Comment by friegger** [comment] 2021-01-14 08:19
The custom intel driver has already been removed for bionic with https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/fc0a38a419c3a57a664a8b6459330387bc6240c1.

**Comment by friegger** [comment] 2021-05-06 11:21
Closing since this is fixed with bionic stemcells.

**Closed by friegger** 2021-05-06 11:21 UTC
Labels: unscheduled
