### ISSUE TITLE
rsyslog crash on bosh-google-kvm-ubuntu-jammy-go_agent/1.18

### ISSUE THREAD

**Issue by nicregez** [cloudfoundry/bosh-linux-stemcell-builder#249] opened 2022-10-27 14:18 UTC
### Summary

I suggest to consider and evaluate rsyslog-openssl as replacement for rsyslog-gnutls.

### Background

We had an `rsyslog` crash on one of our bosh managed VMs recently. This was not the first time the `rsyslog` daemon crashed, but unfortunately, I do not have more details on these older incidents. 

```
# journalctl | grep "Oct 23 05:00:41" | head -1
Oct 23 05:00:41 <vm guid> rsyslogd[263401]: omrelp[34.122.98.95:10515]: error 'TLS record reception failed [gnutls error -54: Error in the pull function.]', object  'conn to srvr 34.122.98.95:10515' - action may not work as intended [v8.2112.0 try https://www.rsyslog.com/e/2353 ]
```

I looked up [OMRELP Manual](https://www.rsyslog.com/doc/v8-stable/configuration/modules/omrelp.html) which says that
> If you have problems with the default setting, we recommend to switch to “openssl”.

This is the [Reference for Error 2353](https://www.rsyslog.com/?s=error+2353).

**Comment by rkoster** [comment] 2022-10-27 14:53
@Benjamintf1 Would you have a problem with the Jammy stemcell switching to openssl as a tls backend for rsyslog?

**Comment by rkoster** [comment] 2022-10-27 14:54
cc @ctlong

**Comment by Benjamintf1** [comment] 2022-10-28 15:54
The most immediate and quick answer is...I don't know?

The longer version is, off the top of my head and through immediate research, I don't have an inclination to say which is better or worse. I think I experimented with it and had trouble when trying to fix jammy, but I fixed it by fixing other settings on the receiver which seemed to have changed. 

The easiest fix would be to setup a option to switch to openssl as the backend, but I'm not sure if that's sufficient to solve the problem or if it would require larger fixes. We have a pipeline setup with tests running against xenial, bionic, and jammy, so we should be able to run tests against any pr to insure it works on all of those stemcells at the moment. 

Broadly speaking, I'm pretty amiable to different solutions, as long as it passes the existing ci.

**Comment by Benjamintf1** [comment] 2022-11-02 18:21
We looked into it a little bit deeper, not only would you likely have to change quite a bit of the configuration to match the new network driver in syslog-release, but our current way of using the `obsolete legacy directives` in syslog-release are not even documented to work in the omrelp documentation. 

While we have not made changes to remove relp, it has gotten a lot less support as a usecase compared to `tcp/tls`. We don't even have a [test for relp at the moment](https://github.com/cloudfoundry/syslog-release/tree/main/tests/manifests). Broader industry support for relp is pretty low, and it doesn't seem to bring much to the table as a protocol. We should probably consider removing relp as a protocol from syslog-release. 

That said, have you considered switching to tcp/tls?

**Comment by h0nIg** [comment] 2022-11-03 09:50
@Benjamintf1 TCP is not 100% reliable, which might be required for audit relevant informations

https://rainer.gerhards.net/2008/05/why-you-cant-build-reliable-tcp.html
https://rainer.gerhards.net/2008/04/on-unreliability-of-plain-tcp-syslog.html

In addition big OS vendors have dedicated help / support for relp because of those requirements:
e.g. https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/deployment_guide/s2-using_relp

On top of that rsyslog is aware of the problems with gnutls and heavily recommends to use openssl: https://github.com/rsyslog/rsyslog/issues/3915

The issue needs to be splitted into 2 dedicated "problems", the connection abort problem and the actual crash caused by the connection abort.

The connection abort was caused by bad TCP keepalive settings by the remote server and frequent connection aborts. There are even connection aborts with openssl without crash. Connection aborts can happen any time and therefore this is unrelevant here and needs to be fixed by the remote server.

This issue fix is about the crash of the rsyslog and the used implementation, the crash will be fixed with https://github.com/cloudfoundry/bosh-linux-stemcell-builder/pull/254

**Comment by Benjamintf1** [comment] 2022-11-03 16:43
https://github.com/cloudfoundry/bosh-linux-stemcell-builder/pull/254/files#diff-b8c04108127281571c1e72921b036f853d2e481fe88c5b43a189a454eecac841R18

In so far as this, are you sure this functions as expected? 

specifically in combination with [the tls parameters](https://github.com/cloudfoundry/syslog-release/blob/ce48957f1145ab87706212baeadd9924d305d7b3/jobs/syslog_forwarder/templates/syslog-release-forwarding-setup.conf.erb#L79-L82), and [the pre-existing import within syslog release](https://github.com/cloudfoundry/syslog-release/blob/ce48957f1145ab87706212baeadd9924d305d7b3/jobs/syslog_forwarder/templates/syslog-release-forwarding-rules.conf.erb#L22)(weird that this line exists at all given apparently the  line has been within the stemcell builder for 6 years, this is probubly where having a relp test would help perhaps?).

**Comment by h0nIg** [comment] 2022-11-07 09:21
@Benjamintf1 

> In so far as this, are you sure this functions as expected?

yes we tested this in SAP for nailing down the issue. On top of that the new rainerscript and the old syntax will co-exist and even ubuntu upstream uses old/new syntax in parallel: https://github.com/cloudfoundry/bosh-linux-stemcell-builder/pull/254#issuecomment-1305313685

> specifically in combination with the tls parameters

The existing gtls usage will not get touched, therefore will continue to work. But you are right, it absolutely makes sense to switch to openssl there as well: https://www.rsyslog.com/doc/v8-stable/configuration/modules/omfwd.html
`If StreamDriver is set to “ossl” or “gtls” it will use TLS-encrypted syslog.`
-> https://github.com/cloudfoundry/syslog-release/pull/100 but we should keep this PR separated from the bosh release changes

**Comment by h0nIg** [comment] 2022-11-07 12:13
PR for bionic as well: @ramonskie https://github.com/cloudfoundry/bosh-linux-stemcell-builder/pull/255

**Comment by nicregez** [comment] 2022-11-07 17:03
Thank you Ruben, Benjamin, Carson for your input and discussions.
The PR provided by @h0nIg for Jammy has been use to create an AWS stemcell and tested in one of our environments.
The configuration works, the process `rsyslogd` is able to load the correct shared libs and metrics get properly shipped using RELP.
Do you require any additional input from our side?
I would be happy if you could merge the two PRs, that would perfectly resolve the present issue.

**Comment by nicregez** [comment] 2022-11-18 06:57
Thanks for merging the two PRs [254](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/pull/254) and [255](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/pull/255)

**Comment by ramonskie** [comment] 2022-11-21 11:31
these will be merged in to the 1.x release branch later on in the next release cycle in 2 weeks or when there is a new high cve reported

**Closed as completed by ramonskie** 2022-11-21 11:31 UTC
